### ISSUE TITLE
Intended use of the `fitted` parameter?

### ISSUE THREAD

**Issue by hrzn** [Nixtla/statsforecast#170]
The introduction of the `fitted` parameter in the methods `croston_classic, croston_optimized, croston_sba` are breaking the Darts implementation. We will fix it on our side, but I was wondering - what's the intended use of this parameter? It seems an exception would be thrown if set to True anyway.

**Comment by kdgutier** [comment]
Hi @hrzn, can you give us some code example on the problem. 
We can take a look and fix it next week.

**Comment by FedericoGarza** [comment]
Hi @hrzn! Thanks for letting us know about the issue. The `fitted` parameter allows returning the fitted values of the model. Since we need the argument in the `StatsForecast` class, all the models have it even if the functionality is not available yet (that's why it throws an exception). We are working on refactoring the models to a more `sklearn` syntax, so maybe the best way to fix the issue right now is to freeze the `statsforecast` version used by `barts` (eg. `0.6.0`).

**Comment by hrzn** [comment]
Thanks guys, we'll fix to `0.6.0` for now
