### ISSUE TITLE
[Bug] Can not use StatsForecast.forecast and Exogenous Regressors

### ISSUE THREAD

**Issue by MariaBocsa** [Nixtla/statsforecast#308]
### What happened + What you expected to happen

Hi,

I tried to use StatsForecast library for my personal dataframe, following the example with exogenous regressors from this link https://nixtla.github.io/statsforecast/examples/exogenous.html , but when I want to use the 'StatsForecast.forecast'  to make predictions, I get the following error:   "ValueError: xreg is rank deficient"
I have weekly data and I want to predict 4 weeks ahead.

Any help is greatly appreciated! 
Thank you!

### Versions / Dependencies

Versions: 
python=3.9.13
statsforecast=1.3.0
pandas=1.4.0
numpy=1.22.0

### Reproduction script

Here is the train dataframe : 
![image](https://user-images.githubusercontent.com/59848550/202151995-8cbfa650-7725-4652-85cc-8221f3da053f.png)
and the test dataframe, that include the future exogenous regressors:
![image](https://user-images.githubusercontent.com/59848550/202152238-a59b4f0d-caf2-49b6-b9b9-e6775f635927.png)

Define/Train the model:
```
horizon=4
models = [AutoARIMA(season_length=52)]

fcst = StatsForecast(df=train, 
                     models=models, 
                     freq='W-MON', 
                     n_jobs=-1)

pred_df = fcst.forecast(horizon, X_df=test)
pred_df
```

**Comment by mergenthaler** [comment]
Hi @MariaBocsa, to give you a complete answer, we might need to look at your data. 

It is normally a bad idea to have an exogenous variable like the one we put in the example. Most of the time, adding an index (1 to 267) as an extra variable will not improve accuracy and will probably cause optimization errors. (In the Air Passengers dataset things work fine because the series has a clear linear trend)

My guess is that your data is not like air passenger data, and therefore you are encountering optimization errors when passing the trend variable as 1 to 267. 

You will also encounter errors if your exogenous variable is linearly dependent to your `y` values. This is because optimization is not possible if the matrix is not invertible. EG (If you have a signal that can be fully explained by your trend)

**Comment by kdgutier** [comment]
From the StatsForecast declaration of the exogenous regressors matrix:
<img width="684" alt="Screenshot 2022-11-16 at 2 38 38 PM" src="https://user-images.githubusercontent.com/19935241/202278358-9911e431-60ab-48e6-8b55-bd7c7a84365a.png">

Two ideas come to my mind:
1) That the number of rows/temporal observations in some of your examples is too small and the intercept of [1,1,1,1] and the trend [1,2,3,4] are equal: [1,1].
2) That by some chance you are using the dates as input that once transformed to numpy are collinear with the trend.

**Comment by MariaBocsa** [comment]
> Hi @mergenthaler sorry for the late response. You are right, the trend was not suitable for my dataset. I solved the problem with other added features. 
Thank you!
