### ISSUE TITLE
[Models]: provide an (non-auto)ARIMA model class as well 

### ISSUE THREAD

**Issue by itchingpixels** [Nixtla/statsforecast#379]
### Description

We'd find it useful if we could:
1. re-use the parameters found by AutoARIMA
2. sometimes, simply provide the parameters ourselves

and use your efficient implementation, instead of statsmodel's.
We think this could be achieved by providing a simple ARIMA class that we can use to manual input parameters to the ARIMA model (we do understand that there's a function we could use, but it looks like the class interface is the canonical way to access it).

Thank you!

**Comment by canbooo** [comment]
Came here to raise this exact issue. Here is a use case: I would like to obtain the results of the auto search (i.e. `model_["arma"]`) once using a training set but keep these results constant during cross-validation with a validation/dev set since the search takes quite long time with longer time series.  Although the effect is not as large, similar arguments could be made about the other auto-models. Alternatively, allow setting `p, q, d, P, Q, D` to constant values or allow partial update of the model without the search.
