### ISSUE TITLE
[sf.plot] Error: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.

### ISSUE THREAD

**Issue by mark-conway** [Nixtla/statsforecast#623]
### What happened + What you expected to happen

Running the example here:

https://nixtla.github.io/statsforecast/docs/getting-started/getting_started_complete.html

This line:

`sf.plot(Y_df,forecasts_df)`

**Error:**

Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.

### Versions / Dependencies

statsforecast 1.6.0
pandas 2.0.3
matplotlib 3.4.0

### Reproduction script

Please refer to link above.

https://nixtla.github.io/statsforecast/docs/getting-started/getting_started_complete.html

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Hey @mark-conway, thanks for using statsforecast. Are you able to provide more details like your Python version and maybe the full traceback? Also your environment may be broken because [pandas 2.0.3 requires matplotlib>=3.6.1](https://github.com/pandas-dev/pandas/blob/0f437949513225922d851e9581723d82120684a6/pyproject.toml#L77), so maybe upgrading matplotlib will solve the issue.

**Comment by mark-conway** [comment]
Thanks @jmoralez I'm going to try the Plotly engine as well.

**Comment by akmalsoliev** [comment]
Hello @mark-conway, thank you for your report, did not think of such a case scenario. Worked on the fix, will push to main after testing.

**Comment by Nilebaba** [comment]
[jmoralez](https://github.com/jmoralez)  说的很有用 很感谢 对于其他版本的pandas要去查看它要求的最低matplotlib版本号
