### ISSUE TITLE
HoltWinters alias parameters not supported and some other problems 

### ISSUE THREAD

**Issue by numomcmc** [Nixtla/statsforecast#733]
Hi

I am following the [HoltWinter ](https://nixtlaverse.nixtla.io/statsforecast/docs/models/holtwinters.html#instantiating-model) example.  The following lines

`season_length = 24 # Hourly data` 
`horizon = len(test) # number of predictions`

`models = [HoltWinters(season_length=season_length, error_type="A", alias="Add"),
          HoltWinters(season_length=season_length, error_type="M", alias="Multi")]`

1. I found the explanation on `season_length` to be extremely confusing.  What's definitive, regardless of the scenario, is the granularity of each user's data, might it be hourly, daily, or what not.  So it'd have been much easier to structure the calls from that perspective.  The fact you had to refer the reader to Hyndman's suggested that it's common to be confused by this feature.

2. the `alias` parameter returns an error.  Shift+Tab on `HoltWinters` revealed that only `season_length` and `error_type` are accepted.  So this example is out of date and invalid.  So already, I can remove `alias`, but then I ran into other problem later.

3. Yet, when I tried to fit the model with `StatsForecast(models=[Add,Multi])`, I am stuck with having no model name/alias to pass into the call.  

4. What is the purpose of calling `StatsForecast(models=[Add,Multi])` after a model has been fitted?  Why not included this in the constructor call?  And if I call this line after the fit, how does it go back to tie with the model?
5. the line `result=sf.fitted_[0,0].model_` returns an error saying that the method `fitted_` does not exist.
6. I just installed StatsForecast via conda yesterday, so it should be a recent stable release.

Thank you for your help.  I really want to support your library, but so far, the documentation has been extremely trying and difficult to follow.  If there's something I can do to help ease the user experience, please let me know.

Best,
Stefan

**Comment by jmoralez** [comment]
Hey @numomcmc, thanks for using statsforecast.

1. The season length is the length of the seasonal period, so if you have hourly data it can be 24 (same hour every day) or 24 * 7 (same hour, same day of the week), etc.
2. The alias is in the constructor, so maybe you installed an older version. Can you check your installed version? https://github.com/Nixtla/statsforecast/blob/89f2e027b4a5d601389847075cdcf942f3a917b5/statsforecast/models.py#L2580-L2608
3. Not sure what you mean by "I am stuck with having no model name/alias to pass into the call"
4. That's not a call, it's the output of the fit method (it returns self).
5. The `fitted_` attribute stores the trained models, so it should be there after you call fit (assuming you're storing the forecast object in `sf`).
6. I don't think you installed a recent version, since the alias has been there [since last year](https://github.com/Nixtla/statsforecast/blame/89f2e027b4a5d601389847075cdcf942f3a917b5/statsforecast/models.py#L2608)

If you're just starting out I recommend a more general guide, like the [quick start](https://nixtlaverse.nixtla.io/statsforecast/docs/getting-started/getting_started_short.html).

**Comment by numomcmc** [comment]
Hi Jose

Thx for the quick response.  I literally just did a "conda install -c
conda-forge statsforecast" yesterday.

Since there's no way to print out the version of StatsForecat, I checked in
Anaconda and it said I had 1.4!!??  So I reinstalled and tried
re-installing via conda.

And the installation process said 1.4 (see attachment), even though the
conda portal says 1.6 (https://anaconda.org/conda-forge/statsforecast).

So here lies the source of the problem.  I ended up having to pip install
to get 1.6.

Stefan

**Comment by jmoralez** [comment]
> Since there's no way to print out the version of StatsForecat

You can run:
```python
import statsforecast

print(statsforecast.__version__)
```
or in a terminal:
```shell
conda list statsforecast
``` 
or
```shell
pip show statsforecast
```

Maybe you already had it installed, that way conda install would do nothing but tell you that you already have it.

Have your problems been addressed? Can we close this issue?

**Comment by numomcmc** [comment]
Well, I think you need to fix the conda install.  It's installing 1.4.

Also,

stf_models = [HoltWinters(season_length=season_length, error_type="A",
alias='Add'),
              HoltWinters(season_length=season_length, error_type="M",
alias='Multi')]

sf = StatsForecast(df=stf_train,
                   models=stf_models,
                   freq='H',
                   n_jobs=-1)

StatsForecast(models=[Add, Multi]) yielded the following error msg:

---------------------------------------------------------------------------NameError
                                Traceback (most recent call last)
Cell In[96], line 1----> 1 StatsForecast(models=[Add, Multi])
NameError: name 'Add' is not defined


The code is copied directly from the website...

**Comment by jmoralez** [comment]
The install from conda works fine, you can see the files [here](https://anaconda.org/conda-forge/statsforecast/files) and both 1.5.0 and 1.6.0 have been downloaded thousands of times. Also you can run `docker run --rm mambaorg/micromamba:1.5-focal micromamba install -c conda-forge statsforecast` and see that it pulls statsforecast 1.6.0.

The error you're getting is because that's not a cell you should run, that's the output in the documentation. Feel free to join our [slack](https://join.slack.com/t/nixtlaworkspace/shared_invite/zt-135dssye9-fWTzMpv2WBthq8NK0Yvu6A) to ask specific questions. I'm closing this since we didn't find any issues.

**Comment by numomcmc** [comment]
"The error you're getting is because that's not a cell you should run,
that's the output in the documentation. Feel free to join our slack
<https://join.slack.com/t/nixtlaworkspace/shared_invite/zt-135dssye9-fWTzMpv2WBthq8NK0Yvu6A>
to
ask specific questions. I'm closing this since we didn't find any issues."

I thought that statement made no sense from the beginning...  Ah.
