### ISSUE TITLE
AutoARIMA import error

### ISSUE THREAD

**Issue by sbalanoptima** [Nixtla/statsforecast#791]
### What happened + What you expected to happen

ImportError: cannot import name 'AutoARIMA' from 'statsforecast.models' (C:\Users\HP\anaconda3\envs\cml\lib\site-packages\statsforecast\models.py)

### Versions / Dependencies

I installed using pip install statsforecast in Anaconda prompt. No version reported. 

### Reproduction script

from statsforecast.models import AutoARIMA

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Hey @sbalanoptima, thanks for using statsforecast. Can you please check which version you installed? You can do that with the following:
```python
import statsforecast
print(statsforecast.__version__)
```
If you're on Python 3.7 then you may have got an old version. Also, since you're using conda, you can also try `conda install -c conda-forge statsforecast`, that'll check if you have any conflicts in your current environment.
