### ISSUE TITLE
Dead links for several pages in docs

### ISSUE THREAD

**Issue by quant5** [Nixtla/statsforecast#838]
### Description

Several pages fail to load and instead we get an "Oops, there's an error" message.

Interestingly, searching for the topic (e.g., holt-winters) in the search bar causes the page to still show up in the results, suggesting these were valid pages that got indexed, but somehow got removed?

### Link

https://[nixtlaverse.nixtla.io/statsforecast/docs/models/holtwinters.html](https://nixtlaverse.nixtla.io/statsforecast/docs/models/holtwinters.html)
https://[nixtlaverse.nixtla.io/statsforecast/docs/models/holt.html](https://nixtlaverse.nixtla.io/statsforecast/docs/models/holt.html)
https://[nixtlaverse.nixtla.io/statsforecast/docs/models/autotheta.html](https://nixtlaverse.nixtla.io/statsforecast/docs/models/autotheta.html)
https://[nixtlaverse.nixtla.io/statsforecast/docs/models/autoregressive.html](https://nixtlaverse.nixtla.io/statsforecast/docs/models/autoregressive.html)
https://[nixtlaverse.nixtla.io/statsforecast/docs/models/autoces.html](https://nixtlaverse.nixtla.io/statsforecast/docs/models/autoces.html)

**Comment by jmoralez** [comment]
Hey, thanks for raising this.

Those pages do exist but our docs engine isn't able to render them, mostly because of problems with equations. You can see the holt winters [here](https://github.com/Nixtla/docs/blob/docs/statsforecast/docs/models/holtwinters.html.mdx), which has a huge table with equations which is most likely the problem. We'll work on fixing the pages you've provided here.

**Comment by jmoralez** [comment]
Hmm, seems like all of those pages are working now. Feel free to reopen if you're unable to access them again.
