### ISSUE TITLE
How to update fitted Arima model with new values

### ISSUE THREAD

**Issue by eshnEnergiDanmark** [Nixtla/statsforecast#890]
Hello. I have an Arima model that I fit every 10 days or so. With this model I forecast values every 15 min. How can I update the fitted model with the newest data, without refitting it? In MLforecast library this is done through an update function, but I cannot find this in statsforecast

**Comment by jmoralez** [comment]
Hey @eshnEnergiDanmark, thanks for using statsforecast. What mlforecast does is update the target values so that when you predict again the model sees the updated features, the model isn't updated in any way. For statsforecast this is a bit harder because the (univariate) models do the forecast internally, without getting any input, so the way to update these would be to run their parameter optimization for a few more iterations considering the new data, which we don't support at the moment but it's on our roadmap.

Also this is already being tracked in #74, so I'm closing this in favor of that.
